version: 2.1
executors:
  golang:
    docker:
      - image: circleci/golang:1.14

commands:
  setup-image:
    steps:
      - checkout

jobs:
  test:
    executor: golang
    steps:
      - setup-image
      - run: make test
  build:
    executor: golang
    steps:
      - setup-image
      - run: make build

workflows:
  version: 2
  build-test-workflow:
    jobs:
      - test
      - build:
          requires:
            - test
