version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.13-buster
    steps:
      - checkout
      - run: make test
  build:
    docker:
      - image: circleci/golang:1.13-buster
    steps:
      - checkout
      - run: make

workflows:
  version: 2
  build-workflow:
    jobs:
      - test
      - build:
          requires:
            - build
